baseURL = "http://example.org/"
languageCode = "en-us"
title = "Web personal"

[permalinks]
  blog = "/:filename/"

[menu]
  [[menu.main]]
    name = "Inicio"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Categorías"
    url = "/tags/"
    weight = 3

[params]
  # homeText = "Front end developer"
  homeText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent in est faucibus, mollis lacus et, posuere lacus. Donec ligula ligula, ornare quis cursus eu, gravida vel augue. Praesent vestibulum urna velit, ac lacinia magna ultrices eget. Nunc et tellus ornare, congue felis id, volutpat eros. Praesent hendrerit, metus sed ultrices ultrices, nulla massa luctus mauris, at placerat libero neque eu risus."
  dateFormat = "Jan 2, 2006"
