baseURL = "http://example.org/"
languageCode = "en-us"
title = "Frontend developer"

[permalinks]
  blog = "/:filename/"

[menu]
  [[menu.main]]
    name = "Inicio"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4

[params]
  # homeText = "Front end developer"
  homeText = "Apasionado del desarrollo, con experiencia de 12 años en el mundo del desarrollo front. Disfruto trabajando en equipo y tengo buenas habilidades para la comunicación. Me gusta afrontar nuevos retos y dispongo de facilidad para aprender nuevos conceptos y lenguajes de programación."
  dateFormat = "Jan 2, 2006"
