baseURL = "https://javifm.com"
# languageCode = "es-es"
title = "Javier Fernández"

paginate = 12
summaryLength = 10
enableEmoji = true
PygmentsUseClasses = true

DefaultContentLanguage = "es"
[languages]
  [languages.es]
    weight = 1
  [languages.en]
    weight = 2

[permalinks]
  blog = "/:section/:title/"

[languages.es.menu]
  [[languages.es.menu.main]]
    name = "Inicio"
    url = "/"
    weight = 1
  [[languages.es.menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
  # [[languages.es.menu.main]]
  #   name = "Categories"
  #   url = "/categories/"
  #   weight = 3
  # [[languages.es.menu.main]]
  #   name = "Tags"
  #   url = "/tags/"
  #   weight = 4
  [[languages.es.menu.main]]
    name = "Sobre mí"
    url = "/about/"
    weight = 5
  [[languages.es.menu.main]]
    name = "Buscar"
    url = "/search/"
    weight = 6
  [[languages.es.menu.main]]
    name = "Contacto"
    url = "/contact/"
    weight = 7

[languages.en.menu]
  [[languages.en.menu.main]]
    name = "Home"
    url = "/en/"
    weight = 1
  [[languages.en.menu.main]]
    name = "Blog"
    url = "/en//blog/"
    weight = 2
  # [[languages.en.menu.main]]
  #   name = "Categories"
  #   url = "/categories/"
  #   weight = 3
  # [[languages.en.menu.main]]
  #   name = "Tags"
  #   url = "/en/tags/"
  #   weight = 4
  [[languages.en.menu.main]]
    name = "About"
    url = "/en/about/"
    weight = 5
  [[languages.en.menu.main]]
    name = "Search"
    url = "/en/search/"
    weight = 6
  [[languages.en.menu.main]]
    name = "Contact"
    url = "/en/contact/"
    weight = 7
[outputs]
    section = ["JSON", "HTML", "RSS"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
  [markup.tableOfContents]
    ordered = true

[params]
titleHtml = "Javier <span class='text-green-500'>Fernández</span>"
  # .Site.Params.homeText
  # homeText = "Front end developer"
  # homeText = "Apasionado del mundo del desarrollo front. Disfruto programando en Javascript siempre teniendo presente el responsive design y la accesibilidad."
  # dateFormat = "Jan 2, 2006"
